version: "3"

services:
  nchan:
    image: nchan-proxy:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nchan.conf:/etc/nginx/conf.d/nchan.conf
    ports:
      - "80:80"
    environment:
      - HTTP_PORT=8000  # set default HTTP port, then nchan.conf can using 80

  video:
    image: video-mcp-nchan:latest
    restart: always
    ports:
      - "8000"
    environment:
      - VIRTUAL_HOST=video.mcp.io

  demo:
    image: demo-mcp-nchan:latest
    restart: always
    ports:
      - "8000"
    environment:
      - VIRTUAL_HOST=notion.mcp.io,notion_user.mcp.io,httmcp.mcp.io

  jinareader:
    extends:
      service: app
    environment:
      - VIRTUAL_HOST=jinareader.mcp.io
