version: "3"

services:
  nchan:
    # image: lloydzhou/nchan
    build:
      context: .
      dockerfile: docker/Dockerfile.nchan
    volumes:
      - ./docker/nchan.conf:/etc/nginx/http.d/default.conf
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    volumes:
      - ./app/app.py:/app/app.py
    ports:
      - "8000:8000"
    restart: always
