version: "3"

services:
  nchan:
    build:
      context: .
      dockerfile: docker/Dockerfile.nchan
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nchan.conf:/etc/nginx/conf.d/mcp.conf
    ports:
      - "80:8000"
    restart: always

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    volumes:
      - ./app/app.py:/app/app.py
    ports:
      - "8000"
    environment:
      - VIRTUAL_HOST=NotionAPIMCP100.mcp.io,JinaURLContentReaderMCPv100.mcp.io,httmcp.mcp.io
    restart: always
